name: sensor_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  google_maps_flutter: ^2.0.10
  geolocator: ^9.0.0
  flutter_blue_plus: ^1.31.8
  flutter_bluetooth_serial: ^0.4.0
  get: ^4.6.5
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/PANTALLA.png
    - lib/assets/images/LOGO.png
    - lib/assets/images/LOGO2.png
    - lib/assets/images/LOGO22.png
    - lib/assets/images/candadopassword.png
    - lib/assets/images/01.png
    - lib/assets/images/02.png
    - lib/assets/images/03.png
    - lib/assets/images/04.png
    - lib/assets/images/05.png
    - lib/assets/images/06.png
    - lib/assets/images/07.png
    - lib/assets/images/08.png
    - lib/assets/images/09.png
    - lib/assets/images/10.png
    - lib/assets/images/11.png
    - lib/assets/images/12.png
    - lib/assets/images/13.png
    - lib/assets/images/14.png
    - lib/assets/images/15.png
    - lib/assets/images/16.png
    - lib/assets/images/17.png
    - lib/assets/images/18.png
    - lib/assets/images/19.png
    - lib/assets/images/20.png
    - lib/assets/images/21.png
    - lib/assets/images/22.png
    - lib/assets/images/23.png
    - lib/assets/images/24.png
    - lib/assets/images/25.png
    - lib/assets/images/26.png
    - lib/assets/images/27.png
    - lib/assets/images/28.png
    - lib/assets/images/29.png

  fonts:
    - family: Open Sans
      fonts:
        - asset: lib/assets/fonts/Open_Sans/OpenSans-Italic-VariableFont_wdth,wght.ttf
          style: italic
        - asset: lib/assets/fonts/Open_Sans/OpenSans-VariableFont_wdth,wght.ttf
